server:
  port: 80
  spring:
    datasource: # 数据源的相关配置
      url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&failOverReadOnly=false&allowPublicKeyRetrieval=true
      username: root
      password: a2833698
      redis:
        database: 1
        host: 172.17.16.13
        port: 6379

        mybatis:
          configuration:
            log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
